Notes cours 1
barackes/cours-hadoop pull request #4
Opened 2018-03-05 10:23 UTC by darkjinung

Notes du cours du 27.02.2018

> yoannis

2018-03-06 10:22 UTC, stebourbi requested changes

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +NameNode - permet de savoir ou sont stockés les blocks de données que l'on cherche à atteindre
au de cette information, c'est l'ensemble de metadonnées du Filesystem qu'il gere et expose.

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +- Ne stocker pas la donnée
typo

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +- Les fichiers sont traités par blocks (unité atomique d'écriture)
unité atomique de gestion (ecriture/lecture et distribution)

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> + - Permet de mapper les paths aux blocks de notre DD
non!
initialise l'arborescence des path locaux a utiliser.

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +Le fichier .ckpt contient un checkpoint des transactions faites
a retirer detail d'implementation.

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +### Lancement de HDFS
lancement en mode pseudo-distribué.

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +- jps -> process java qui tournent
mettre un exemple de sortie pour un cas ou c'est up and running

2018-03-06 10:22 UTC, stebourbi commented on HDFS.md
> +### Verifier le system de fichier
la verification c'est avec hdfs dfs fsck /
ces commandes c'est juste du requetage.

2018-03-19 01:19 UTC, chefira approved these changes

2018-03-19 01:19 UTC, chefira commented on README.md
> +* *TODO*
Modèle de calcul

2018-03-19 01:50 UTC, merged